# golangci-lint v2 configuration
# See: https://golangci-lint.run/docs/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - nolintlint

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # _ = err is intentional acknowledgment

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Disable fieldalignment globally (optional alternative)

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

  exclusions:
    presets:
      - comments
      - std-error-handling
    
    rules:
      # Exclude lll from test files
      - path: _test\.go
        linters:
          - lll
      
      # Exclude fieldalignment from test files (anonymous structs in tests)
      - path: _test\.go
        text: "fieldalignment"

formatters:
  enable:
    - gofmt
    - goimports